import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "the-new-css-reset/css/reset.css";
import "./globals.css";
import Footer from "./share/Footer";
import Aside from "./share/Aside";
import TopNav from "./share/topNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <TopNav />
        <Aside>{children}</Aside>
        <Footer />
      </body>
    </html>
  );
}
