import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import { Inter } from "next/font/google";
import "the-new-css-reset/css/reset.css";
import "./globals.css";
import Footer from "./share/Footer";
import Aside from "./share/Aside";
import TopNav from "./share/topNav";
import { Provider } from "jotai";

const NotoSansFont = Noto_Sans_KR({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DevCookie",
  description: "Generated by DevCookieCorporation",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={NotoSansFont.className}>
      <body>
        <TopNav />
        <Aside>{children}</Aside>
        <Footer />
      </body>
    </html>
  );
}
